version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./auth
    environment:
      - PORT=3000
      - MONGODB_AUTH_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  product:
    build: ./product
    environment:
      - PORT=3001
      - MONGODB_PRODUCT_URI=mongodb://mongo:27017/product
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - RABBITMQ_ORDER_QUEUE=orders
      - RABBITMQ_PRODUCT_QUEUE=products
      - RABBITMQ_CONNECT_DELAY_MS=20000
      - JWT_SECRET=secret
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq

  order:
    build: ./order
    environment:
      - PORT=3002
      - MONGODB_ORDER_URI=mongodb://mongo:27017/order
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - RABBITMQ_ORDER_QUEUE=orders
      - RABBITMQ_PRODUCT_QUEUE=products
      - RABBITMQ_CONNECT_DELAY_MS=10000
      - JWT_SECRET=secret
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    environment:
      - PORT=3003
      - AUTH_SERVICE_URL=http://auth:3000
      - PRODUCT_SERVICE_URL=http://product:3001
      - ORDER_SERVICE_URL=http://order:3002
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-data:
